# Generated by Django 3.0.5 on 2020-04-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('emp_name', models.CharField(max_length=120)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
