# Generated by Django 3.0.5 on 2020-04-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200408_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emp_description',
            field=models.TextField(null=True),
        ),
    ]
