# Generated by Django 3.0.5 on 2020-04-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200408_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emp_description',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
