# Generated by Django 3.0.5 on 2020-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200408_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emp_description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
