# Generated by Django 3.0.5 on 2020-04-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
