# Generated by Django 3.0.5 on 2020-04-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userid',
        ),
    ]
